# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170717_1152'),
        ('board', '0008_remove_comment_approved_comment'),
    ]

    operations = [
    ]
